// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bc_handball_be.Infrastructure.Persistence;

#nullable disable

namespace bc_handball_be.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250506093442_AddMessageToEventNew")]
    partial class AddMessageToEventNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.ClubAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("ClubAdmin", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("GoalkeeperVoteId")
                        .HasColumnType("int");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerVoteId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Coach", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("GoalCount")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RedCardCount")
                        .HasColumnType("int");

                    b.Property<int>("SevenMeterGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("SevenMeterMissCount")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TwoMinPenaltyCount")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Recorder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Recorder", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Referee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Referee", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.super.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TournamentInstanceId")
                        .HasColumnType("int");

                    b.Property<bool>("VoitingOpen")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentInstanceId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Club", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssistantRefereeId")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("MainRefereeId")
                        .HasColumnType("int");

                    b.Property<string>("Playground")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TimePlayed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssistantRefereeId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("GroupId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("MainRefereeId");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TournamentInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClubId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TournamentInstanceId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tournament", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.TournamentInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EditionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentInstance", (string)null);
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Admin", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithOne()
                        .HasForeignKey("bc_handball_be.Core.Entities.Actors.sub.Admin", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.ClubAdmin", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Club", "Club")
                        .WithOne("ClubAdmin")
                        .HasForeignKey("bc_handball_be.Core.Entities.Actors.sub.ClubAdmin", "ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithOne()
                        .HasForeignKey("bc_handball_be.Core.Entities.Actors.sub.ClubAdmin", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Coach", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Category", "Category")
                        .WithMany("Voting")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Team", "Team")
                        .WithOne("Coach")
                        .HasForeignKey("bc_handball_be.Core.Entities.Actors.sub.Coach", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Player", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Category", "Category")
                        .WithMany("Stats")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Recorder", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithOne()
                        .HasForeignKey("bc_handball_be.Core.Entities.Actors.sub.Recorder", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Referee", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithOne()
                        .HasForeignKey("bc_handball_be.Core.Entities.Actors.sub.Referee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Category", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.TournamentInstance", "TournamentInstance")
                        .WithMany("Categories")
                        .HasForeignKey("TournamentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentInstance");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Event", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Group", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Category", "Category")
                        .WithMany("Groups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Login", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Actors.super.Person", "Person")
                        .WithOne("Login")
                        .HasForeignKey("bc_handball_be.Core.Entities.Login", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Match", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Actors.sub.Referee", "AssistantReferee")
                        .WithMany("AssistantRefereeMatches")
                        .HasForeignKey("AssistantRefereeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("bc_handball_be.Core.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("bc_handball_be.Core.Entities.Group", "Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bc_handball_be.Core.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("bc_handball_be.Core.Entities.Actors.sub.Referee", "MainReferee")
                        .WithMany("MainRefereeMatches")
                        .HasForeignKey("MainRefereeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssistantReferee");

                    b.Navigation("AwayTeam");

                    b.Navigation("Group");

                    b.Navigation("HomeTeam");

                    b.Navigation("MainReferee");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Team", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Club", "Club")
                        .WithMany("Teams")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc_handball_be.Core.Entities.Group", "Group")
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("bc_handball_be.Core.Entities.TournamentInstance", "TournamentInstance")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Club");

                    b.Navigation("Group");

                    b.Navigation("TournamentInstance");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.TournamentInstance", b =>
                {
                    b.HasOne("bc_handball_be.Core.Entities.Tournament", "Tournament")
                        .WithMany("Editions")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.sub.Referee", b =>
                {
                    b.Navigation("AssistantRefereeMatches");

                    b.Navigation("MainRefereeMatches");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Actors.super.Person", b =>
                {
                    b.Navigation("Login");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Category", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Stats");

                    b.Navigation("Voting");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Club", b =>
                {
                    b.Navigation("ClubAdmin");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Group", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Match", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("Coach");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.Tournament", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("bc_handball_be.Core.Entities.TournamentInstance", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
